### ISSUE TITLE
Subroutine LANDROID_GetReadings redefined at ./FHEM/74_LANDROID.pm line 639

### ISSUE THREAD

**Issue by arneman** [axelmohnen/fhem-landroid-s#1]
PERL WARNING: Subroutine LANDROID_GetReadings redefined at ./FHEM/74_LANDROID.pm line 639

I removed the second subroutine and everything still works fine

**Comment by axelmohnen** [comment]
Thanks for the info. I will remove the second subroutine in version 1.3.
The version will be released soon!
