### ISSUE TITLE
Error running "node LandroidSrv.js"

### ISSUE THREAD

**Issue by DanMittendorf** [axelmohnen/fhem-landroid-s#2]
What can I do to fix this problem? Followed the install instructions step by step.

`var adapter = { config: LandroidConf.[mowerId],`
`-------------------------------------^`
`SyntaxError: Unexpected token [`
`    at createScript (vm.js:80:10)`
`    at Object.runInThisContext (vm.js:139:10)`
`    at Module._compile (module.js:616:28)`
`    at Object.Module._extensions..js (module.js:663:10)`
`    at Module.load (module.js:565:32)`
`    at tryModuleLoad (module.js:505:12)`
`    at Function.Module._load (module.js:497:3)`
`    at Function.Module.runMain (module.js:693:10)`
`    at startup (bootstrap_node.js:191:16)`
`    at bootstrap_node.js:612:3`

**Comment by arneman** [comment]
as far as i see, you pulled a faulty version. meanwhile, this error should be already fixed in https://github.com/axelmohnen/fhem-landroid-s/blob/9e988298ed2972e649c4e6ad5bed3bd88638f325/LandroidSrv.js

**Comment by DanMittendorf** [comment]
Thanks. Got it to work :-)
